<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Elektronik</name>
   <tag></tag>
   <elementGuidId>c97c7ea6-9b71-4e5b-b5a3-083ac67639c8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div._6g-ThL</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li//div[text()='Elektronik']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>70373f0a-c4f2-4344-9c51-55838e3284dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_6g-ThL</value>
      <webElementGuid>1d98d5ce-e026-4834-b71f-0ae8d5122472</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Elektronik</value>
      <webElementGuid>1cc13681-5c47-4018-95bd-13656549bf17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main&quot;)/div[@class=&quot;theme--ofs&quot;]/div[2]/div[@class=&quot;YlA+6W uVMF-T&quot;]/div[@class=&quot;official-shop-page md-page&quot;]/div[@class=&quot;container ofs-page__container&quot;]/div[7]/div[@class=&quot;jb081L container&quot;]/div[@class=&quot;image-carousel&quot;]/div[@class=&quot;image-carousel__item-list-wrapper&quot;]/ul[@class=&quot;image-carousel__item-list&quot;]/li[@class=&quot;image-carousel__item&quot;]/a[@class=&quot;Fy9Qcq&quot;]/div[@class=&quot;_6g-ThL&quot;]</value>
      <webElementGuid>34badfe6-e6fb-41eb-a193-210c878283f4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main']/div/div[2]/div/div/div/div[7]/div/div[2]/div/ul/li/a/div[2]</value>
      <webElementGuid>a6a05a9a-1240-41c3-9796-4050abd05d55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/a/div[2]</value>
      <webElementGuid>91b27e74-4368-41dd-8c5d-85301621e56b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Elektronik' or . = 'Elektronik')]</value>
      <webElementGuid>6e3cd48e-cb7e-4fa9-8747-0a0b26620148</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
